# Directs the executor to query only when the field exists.
directive @ifdef on FIELD

type CompletionBoard {
  courseRunId: String!
  students: [StudentCompletion!]!
}

type CompletionRecord {
  labId: String!
  completedAt: String!
}

type Endpoint {
  host: String!
  port: Int!
}

type Lab {
  id: String!
  wsEndpoints: [Endpoint!]!
  tcpEndpoints: [Endpoint!]!
  resources: [ResourceWithTranslation!]!
}

type LabCategory {
  id: String!
  name: [Translation!]!
  labs: [Lab!]!
}

type LabInstance {
  lang: String!
  name: String!
  content: String!
  wsEndpoints: [Endpoint!]!
  tcpEndpoints: [Endpoint!]!
}

type Learning {
  lessonCategories: [LearningCategory!]!
}

type LearningCategory {
  id: String!
  name: [Translation!]!
  lessons: [Lesson!]!
}

type Lesson {
  id: String!
}

type LessonDocuments {
  lesson: String!
  locale: String
}

type Practice {
  labCategories: [LabCategory!]!
}

type Query {
  hello: String!
  practice: Practice!
  learning: Learning!
  lessonDocuments(lessonId: String!, language: String!): LessonDocuments!
  lab(categoryId: String!, labId: String!, language: String): LabInstance!
  completionBoard(courseRunId: String): CompletionBoard!
}

type ResourceWithTranslation {
  lang: String!
  name: String!
}

type StudentCompletion {
  studentId: String!
  completions: [CompletionRecord!]!
}

type Translation {
  lang: String!
  text: String!
}
