schema:
  - "schema/schema.gql"
documents:
  - "src/practice/graphql/**/*.gql"
  - "src/transport/graphql/**/*.gql"
generates:
  src/transport/generated/:
    preset: client
    presetConfig:
      fragmentMasking: false
