query CompletionBoard($courseRunId: String) {
  completionBoard(courseRunId: $courseRunId) {
    courseRunId
    students {
      studentId
      completions {
        labId
        completedAt
      }
    }
  }
}
